name: DevInfra

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  breaking-changes-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: angular/dev-infra/github-actions/breaking-changes-label@4c73d4e8f0a31fd05ae4d32c6a4b661a9dc80567
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
